# Generated by Django 2.2.6 on 2019-10-27 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('birthday', models.CharField(max_length=30)),
                ('edu', models.CharField(max_length=10)),
                ('trade', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('marriage', models.CharField(max_length=10)),
                ('working', models.CharField(max_length=10)),
                ('child', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
