# Generated by Django 2.2.5 on 2020-01-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=10)),
                ('account', models.CharField(max_length=40, unique=True)),
                ('area', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10, null=True)),
                ('county', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('age', models.IntegerField(null=True)),
                ('birthday', models.CharField(max_length=30, null=True)),
                ('edu', models.CharField(max_length=10)),
                ('trade', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('marriage', models.CharField(max_length=10)),
                ('working', models.CharField(max_length=10)),
                ('child', models.IntegerField(max_length=10, null=True)),
                ('child_age', models.IntegerField(null=True)),
                ('child_birthday', models.CharField(max_length=30, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=30)),
                ('personal_monthly_income', models.CharField(max_length=20)),
                ('family_monthly_income', models.CharField(max_length=20, null=True)),
                ('hide_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
