# Generated by Django 2.2.6 on 2019-10-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
