# Generated by Django 2.2.5 on 2020-01-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
