# Generated by Django 2.2.5 on 2020-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0002_auto_20200113_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='county',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='province',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
