# Generated by Django 2.2.6 on 2019-10-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0002_auto_20191028_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['-id']},
        ),
    ]
