# Generated by Django 2.2.6 on 2019-10-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0005_remove_user_password1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_account',
        ),
    ]
