# Generated by Django 2.2.6 on 2019-11-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0007_accounts_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='age',
            field=models.IntegerField(max_length=5),
        ),
    ]
