# Generated by Django 2.2.5 on 2019-12-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0014_auto_20191218_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='child_birthday',
            field=models.CharField(max_length=30),
        ),
    ]
