# Generated by Django 3.0 on 2019-12-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0014_auto_20191216_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child_birthday',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
