# Generated by Django 2.2.5 on 2019-12-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0015_auto_20191218_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='child_birthday',
            field=models.DateField(auto_now_add=True),
        ),
    ]
