# Generated by Django 2.2.5 on 2019-12-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0016_auto_20191218_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child_birthday',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='family_monthly_income',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='personal_monthly_income',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
