# Generated by Django 3.0 on 2019-12-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0016_auto_20191226_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child_birthday',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
