# Generated by Django 3.0 on 2019-12-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0018_accounts_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
