# Generated by Django 3.0 on 2019-12-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0019_auto_20191226_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
