# Generated by Django 2.2.5 on 2019-10-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
    ]
