# Generated by Django 2.2.6 on 2019-11-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0006_auto_20191031_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='age',
            field=models.IntegerField(default=2000, max_length=3),
            preserve_default=False,
        ),
    ]
