# Generated by Django 2.2.5 on 2019-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0008_auto_20191108_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='age',
            field=models.IntegerField(),
        ),
    ]
