# Generated by Django 2.2.5 on 2019-11-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0009_auto_20191111_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='family_monthly_inconme',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='personal_monthly_income',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
