# Generated by Django 2.2.5 on 2019-11-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0010_auto_20191111_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='family_monthly_inconme',
            new_name='family_monthly_income',
        ),
    ]
