# Generated by Django 2.2.5 on 2019-11-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0011_auto_20191111_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='child_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='child_birthday',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
