# Generated by Django 2.2.5 on 2019-12-13 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0012_auto_20191114_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='hide_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
