# Generated by Django 3.0 on 2019-12-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0013_accounts_hide_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='hide_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
