# Generated by Django 3.0 on 2019-12-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0015_auto_20191225_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='child_birthday',
            field=models.DateField(null=True),
        ),
    ]
