# Generated by Django 2.2.5 on 2020-01-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0017_auto_20191225_1632'),
        ('account_list', '0020_auto_20191226_1623'),
    ]

    operations = [
    ]
