# Generated by Django 2.2.5 on 2020-01-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0022_auto_20200113_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='child',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='family_monthly_income',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
