# Generated by Django 2.2.5 on 2020-01-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0023_auto_20200113_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
