# Generated by Django 2.2.6 on 2019-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=40)),
                ('erea', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('birthday', models.IntegerField()),
                ('edu', models.CharField(max_length=10)),
                ('trade', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('marriage', models.CharField(max_length=10)),
                ('working', models.CharField(max_length=10)),
                ('child', models.IntegerField()),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
