# Generated by Django 2.2.6 on 2019-10-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_list', '0002_auto_20191027_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.CharField(max_length=30),
        ),
    ]
